// import { Category, Product } from '@/types';

// export const seedCategories: Omit<Category, 'id' | 'created_at'>[] = [
//   {
//     name: "Men's Shoes",
//     slug: 'mens-shoes',
//     description: 'Explore our collection of men\'s shoes, designed for performance and style.',
//     image_url: 'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/mens-shoes/flying-colorful-womens-sneaker-isolated-on-white-background-fashionable-stylish-sports-shoe.jpg',
//   },
//   {
//     name: "Women's Shoes",
//     slug: 'womens-shoes',
//     description: 'Discover stylish and comfortable women\'s shoes for every occasion.',
//     image_url: 'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/womens-shoes/pexels-photo-134064.jpeg',
//   },
//   {
//     name: "Kids' Shoes",
//     slug: 'kids-shoes',
//     description: 'Fun and durable shoes for kids of all ages.',
//     image_url: 'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/kids-shoes/pexels-photo-1598505.jpeg',
//   },
//   {
//     name: "Running Shoes",
//     slug: 'running-shoes',
//     description: 'High-performance running shoes for all terrains and distances.',
//     image_url: 'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/running-shoes/pexels-photo-267320.jpeg',
//   },
//   {
//     name: "Basketball Shoes",
//     slug: 'basketball-shoes',
//     description: 'Dominate the court with our advanced basketball shoe collection.',
//     image_url: 'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/basketball-shoes/photo-1525966222134-fcfa99b8ae77.jpg',
//   },
// ];

// export const seedProducts: Omit<Product, 'id' | 'created_at' | 'updated_at' | 'category'>[] = [
//   {
//     name: 'Nike Air Max 270',
//     slug: 'nike-air-max-270',
//     description: 'Experience ultimate comfort with the Nike Air Max 270. Featuring Nike\'s largest heel Air unit yet, it delivers a super-soft ride that feels as impossible as it looks.',
//     price: 150.00,
//     sale_price: 120.00,
//     category_id: '', // Will be filled dynamically
//     brand: 'Nike',
//     colors: ['Black', 'White', 'Red'],
//     sizes: ['7', '8', '9', '10', '11', '12'],
//     images: [
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/mens-shoes/pexels-photo-1027130.jpeg',
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/mens-shoes/pexels-photo-1032110.jpeg',
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/mens-shoes/pexels-photo-1102777.jpeg',
//     ],
//     stock: 50,
//     is_featured: true,
//     is_new: true,
//     rating: 4.8,
//     reviews_count: 124,
//   },
//   {
//     name: 'Adidas Ultraboost 22',
//     slug: 'adidas-ultraboost-22',
//     description: 'The Ultraboost 22 delivers incredible energy return and comfort. Designed for a women\'s specific fit, it provides a responsive ride for your daily runs.',
//     price: 190.00,
//     sale_price: null,
//     category_id: '', // Will be filled dynamically
//     brand: 'Adidas',
//     colors: ['White', 'Black', 'Pink'],
//     sizes: ['6', '7', '8', '9', '10'],
//     images: [
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/womens-shoes/pexels-photo-134064.jpeg',
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/womens-shoes/pexels-photo-137603.jpeg',
//     ],
//     stock: 35,
//     is_featured: true,
//     is_new: false,
//     rating: 4.6,
//     reviews_count: 89,
//   },
//   {
//     name: 'Puma RS-X Reinvention',
//     slug: 'puma-rs-x-reinvention',
//     description: 'The RS-X Reinvention is all about reinvention. With a bulky silhouette and bold material mixes, these kicks are ready to take your style to the next level.',
//     price: 110.00,
//     sale_price: 99.99,
//     category_id: '', // Will be filled dynamically
//     brand: 'Puma',
//     colors: ['Grey', 'Blue', 'Orange'],
//     sizes: ['7', '8', '9', '10', '11'],
//     images: [
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/casual-sneakers/photo-1595341888016-a392ef81b7de.jpg',
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/casual-sneakers/photo-1595950653106-6c9ebd614d3a.jpg',
//     ],
//     stock: 28,
//     is_featured: false,
//     is_new: true,
//     rating: 4.5,
//     reviews_count: 70,
//   },
//   {
//     name: 'New Balance 990v5',
//     slug: 'new-balance-990v5',
//     description: 'The 990v5 combines superior cushioning and stability in a classic design. Perfect for running or everyday wear, it\'s a true icon.',
//     price: 175.00,
//     sale_price: null,
//     category_id: '', // Will be filled dynamically
//     brand: 'New Balance',
//     colors: ['Navy', 'Grey', 'Black'],
//     sizes: ['8', '9', '10', '11', '12', '13'],
//     images: [
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/running-shoes/pexels-photo-267320.jpeg',
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/running-shoes/pexels-photo-292998.jpeg',
//     ],
//     stock: 42,
//     is_featured: true,
//     is_new: false,
//     rating: 4.9,
//     reviews_count: 156,
//   },
//   {
//     name: 'Converse Chuck 70',
//     slug: 'converse-chuck-70',
//     description: 'The Chuck 70 is a re-crafted classic that blends vintage-inspired details with modern comfort updates.',
//     price: 80.00,
//     sale_price: null,
//     category_id: '', // Will be filled dynamically
//     brand: 'Converse',
//     colors: ['Black', 'White', 'Red', 'Navy'],
//     sizes: ['5', '6', '7', '8', '9', '10', '11'],
//     images: [
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/casual-sneakers/photo-1600185365926-3a2ce3cdb9eb.jpg',
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/casual-sneakers/photo-1606107557195-0e29a4b5b4aa.jpg',
//     ],
//     stock: 60,
//     is_featured: false,
//     is_new: true,
//     rating: 4.7,
//     reviews_count: 98,
//   },
//   {
//     name: 'Vans Old Skool',
//     slug: 'vans-old-skool',
//     description: 'The Old Skool, Vans classic skate shoe and the first to bear the iconic sidestripe, is a low top lace-up featuring sturdy canvas and suede uppers.',
//     price: 70.00,
//     sale_price: null,
//     category_id: '', // Will be filled dynamically
//     brand: 'Vans',
//     colors: ['Black', 'White', 'Checkerboard'],
//     sizes: ['6', '7', '8', '9', '10', '11'],
//     images: [
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/running-shoes/pexels-photo-267320.jpeg',
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/running-shoes/pexels-photo-292999.jpeg',
//     ],
//     stock: 55,
//     is_featured: false,
//     is_new: false,
//     rating: 4.6,
//     reviews_count: 75,
//   },
//   {
//     name: 'Reebok Club C 85',
//     slug: 'reebok-club-c-85',
//     description: 'A true tennis-inspired classic, the Club C 85 features a soft leather upper and a durable rubber outsole for timeless style and comfort.',
//     price: 75.00,
//     sale_price: 60.00,
//     category_id: '', // Will be filled dynamically
//     brand: 'Reebok',
//     colors: ['White', 'Green', 'Navy'],
//     sizes: ['7', '8', '9', '10'],
//     images: [
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/mens-shoes/pexels-photo-1159670.jpeg',
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/mens-shoes/pexels-photo-1240892.jpeg',
//     ],
//     stock: 40,
//     is_featured: true,
//     is_new: true,
//     rating: 4.4,
//     reviews_count: 60,
//   },
//   {
//     name: 'Asics Gel-Kayano 29',
//     slug: 'asics-gel-kayano-29',
//     description: 'The GEL-KAYANO 29 creates a stable running experience and a more responsive feel underfoot. It\'s a great choice for overpronators.',
//     price: 160.00,
//     sale_price: null,
//     category_id: '', // Will be filled dynamically
//     brand: 'Asics',
//     colors: ['Blue', 'Black', 'Silver'],
//     sizes: ['7', '8', '9', '10', '11', '12'],
//     images: [
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/running-shoes/pexels-photo-292998.jpeg',
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/running-shoes/pexels-photo-637076.jpeg',
//     ],
//     stock: 30,
//     is_featured: false,
//     is_new: false,
//     rating: 4.7,
//     reviews_count: 110,
//   },
//   {
//     name: 'Brooks Ghost 15',
//     slug: 'brooks-ghost-15',
//     description: 'The Ghost 15 offers a smooth ride and soft cushioning, making it a favorite for runners seeking comfort and reliability.',
//     price: 140.00,
//     sale_price: 115.00,
//     category_id: '', // Will be filled dynamically
//     brand: 'Brooks',
//     colors: ['Grey', 'Blue', 'Coral'],
//     sizes: ['6', '7', '8', '9', '10', '11'],
//     images: [
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/running-shoes/pexels-photo-786003.jpeg',
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/running-shoes/pexels-photo.jpg',
//     ],
//     stock: 45,
//     is_featured: true,
//     is_new: true,
//     rating: 4.8,
//     reviews_count: 130,
//   },
//   {
//     name: 'Hoka Clifton 9',
//     slug: 'hoka-clifton-9',
//     description: 'The Clifton 9 delivers a lighter, more cushioned experience. Eliminating weight while adding 3mm to stack height, the new Clifton delivers a revitalized underfoot experience.',
//     price: 145.00,
//     sale_price: null,
//     category_id: '', // Will be filled dynamically
//     brand: 'Hoka',
//     colors: ['Black', 'White', 'Green'],
//     sizes: ['7', '8', '9', '10', '11'],
//     images: [
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/running-shoes/photo-1491553895911-0055eca6402d.jpg',
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/running-shoes/photo-1512374382149-233c42b6a83b.jpg',
//     ],
//     stock: 25,
//     is_featured: false,
//     is_new: false,
//     rating: 4.9,
//     reviews_count: 95,
//   },
//   {
//     name: 'Mizuno Wave Rider 26',
//     slug: 'mizuno-wave-rider-26',
//     description: 'The Wave Rider 26 offers a smooth and energetic ride, perfect for daily training. Its MIZUNO ENERZY FOAM provides soft cushioning and high energy return.',
//     price: 130.00,
//     sale_price: 100.00,
//     category_id: '', // Will be filled dynamically
//     brand: 'Mizuno',
//     colors: ['Blue', 'Yellow', 'Black'],
//     sizes: ['7', '8', '9', '10', '11', '12'],
//     images: [
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/basketball-shoes/photo-1525966222134-fcfa99b8ae77.jpg',
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/basketball-shoes/photo-1529810313688-44ea1c2d81d3.jpg',
//     ],
//     stock: 38,
//     is_featured: false,
//     is_new: true,
//     rating: 4.5,
//     reviews_count: 80,
//   },
//   {
//     name: 'Saucony Kinvara 14',
//     slug: 'saucony-kinvara-14',
//     description: 'The Kinvara 14 is lighter than ever, with enough PWRRUN cushioning to handle your daily miles and a snappy feel for faster efforts.',
//     price: 120.00,
//     sale_price: null,
//     category_id: '', // Will be filled dynamically
//     brand: 'Saucony',
//     colors: ['Green', 'White', 'Purple'],
//     sizes: ['6', '7', '8', '9', '10'],
//     images: [
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/basketball-shoes/photo-1539185441755-769473a23570.jpg',
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/basketball-shoes/photo-1543163521-1bf539c55dd2.jpg',
//     ],
//     stock: 32,
//     is_featured: true,
//     is_new: false,
//     rating: 4.6,
//     reviews_count: 72,
//   },
//   {
//     name: 'Under Armour Flow Velociti Wind 2',
//     slug: 'under-armour-flow-velociti-wind-2',
//     description: 'The UA Flow Velociti Wind 2 is a fast, light, and grippy running shoe that eliminates the rubber outsole, giving you a direct connection to the ground.',
//     price: 160.00,
//     sale_price: 130.00,
//     category_id: '', // Will be filled dynamically
//     brand: 'Under Armour',
//     colors: ['Black', 'Red', 'Blue'],
//     sizes: ['8', '9', '10', '11', '12'],
//     images: [
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/basketball-shoes/photo-1543508282-6319a3e2621f.jpg',
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/basketball-shoes/photo-1549298916-b41d501d3772.jpg',
//     ],
//     stock: 20,
//     is_featured: false,
//     is_new: true,
//     rating: 4.7,
//     reviews_count: 65,
//   },
//   {
//     name: 'Nike Blazer Mid \'77 Vintage',
//     slug: 'nike-blazer-mid-77-vintage',
//     description: 'The Nike Blazer Mid \'77 Vintage harnesses the old-school look of Nike basketball. Its luscious suede accents, retro Swoosh design and padded collar make it a modern staple.',
//     price: 100.00,
//     sale_price: null,
//     category_id: '', // Will be filled dynamically
//     brand: 'Nike',
//     colors: ['White', 'Black', 'Green'],
//     sizes: ['7', '8', '9', '10', '11'],
//     images: [
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/basketball-shoes/photo-1551107696-a4b0c5a0d9a2.jpg',
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/basketball-shoes/photo-1560769629-975ec94e6a86.jpg',
//     ],
//     stock: 50,
//     is_featured: true,
//     is_new: false,
//     rating: 4.8,
//     reviews_count: 100,
//   },
//   {
//     name: 'Adidas Stan Smith',
//     slug: 'adidas-stan-smith',
//     description: 'Clean, crisp, and iconic. The Stan Smith has been an icon for over 50 years, and this version continues the legacy with a fresh look.',
//     price: 90.00,
//     sale_price: null,
//     category_id: '', // Will be filled dynamically
//     brand: 'Adidas',
//     colors: ['White', 'Green', 'Navy'],
//     sizes: ['6', '7', '8', '9', '10', '11'],
//     images: [
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/womens-shoes/pexels-photo-1407354.jpeg',
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/womens-shoes/pexels-photo-1445696.jpeg',
//     ],
//     stock: 60,
//     is_featured: false,
//     is_new: true,
//     rating: 4.7,
//     reviews_count: 85,
//   },
//   {
//     name: 'Puma Suede Classic',
//     slug: 'puma-suede-classic',
//     description: 'The PUMA Suede is a true icon. It\'s been around since 1968 and has been worn by generations of B-boys, artists, and athletes.',
//     price: 65.00,
//     sale_price: null,
//     category_id: '', // Will be filled dynamically
//     brand: 'Puma',
//     colors: ['Black', 'Red', 'Blue', 'Green'],
//     sizes: ['7', '8', '9', '10'],
//     images: [
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/womens-shoes/pexels-photo-1449844.jpeg',
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/womens-shoes/pexels-photo-1478442.jpeg',
//     ],
//     stock: 70,
//     is_featured: false,
//     is_new: false,
//     rating: 4.5,
//     reviews_count: 90,
//   },
//   {
//     name: 'Nike Air Force 1 \'07',
//     slug: 'nike-air-force-1-07',
//     description: 'The radiance lives on in the Nike Air Force 1 \'07, the b-ball OG that puts a fresh spin on what you know best: crisp overlays, bold accents and the perfect amount of flash to make you shine.',
//     price: 110.00,
//     sale_price: null,
//     category_id: '', // Will be filled dynamically
//     brand: 'Nike',
//     colors: ['White', 'Black'],
//     sizes: ['7', '8', '9', '10', '11', '12'],
//     images: [
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/mens-shoes/pexels-photo-1280064.jpeg',
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/mens-shoes/pexels-photo-1335463.jpeg',
//     ],
//     stock: 80,
//     is_featured: true,
//     is_new: true,
//     rating: 4.9,
//     reviews_count: 200,
//   },
//   {
//     name: 'Adidas Gazelle',
//     slug: 'adidas-gazelle',
//     description: 'A true classic, the Gazelle has been a favorite for decades. This version brings back the iconic look with a soft suede upper and contrasting 3-Stripes.',
//     price: 85.00,
//     sale_price: null,
//     category_id: '', // Will be filled dynamically
//     brand: 'Adidas',
//     colors: ['Blue', 'Red', 'Green'],
//     sizes: ['6', '7', '8', '9', '10', '11'],
//     images: [
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/womens-shoes/pexels-photo-1503009.jpeg',
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/womens-shoes/pexels-photo-15300927.jpeg',
//     ],
//     stock: 40,
//     is_featured: false,
//     is_new: false,
//     rating: 4.6,
//     reviews_count: 78,
//   },
//   {
//     name: 'Nike Dunk Low Retro',
//     slug: 'nike-dunk-low-retro',
//     description: 'Created for the hardwood but taken to the streets, the \'80s icon returns with perfectly shined overlays and original team colors. With its iconic hoops design, the Nike Dunk Low Retro channels vintage style back to the streets.',
//     price: 110.00,
//     sale_price: null,
//     category_id: '', // Will be filled dynamically
//     brand: 'Nike',
//     colors: ['White', 'Black', 'Red', 'Blue'],
//     sizes: ['7', '8', '9', '10', '11', '12'],
//     images: [
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/kids-shoes/pexels-photo-1598508.jpeg',
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/kids-shoes/pexels-photo-186035.jpeg',
//     ],
//     stock: 30,
//     is_featured: true,
//     is_new: true,
//     rating: 4.8,
//     reviews_count: 180,
//   },
//   {
//     name: 'Jordan 1 Mid',
//     slug: 'jordan-1-mid',
//     description: 'Inspired by the original AJ1, the Air Jordan 1 Mid offers fans a chance to follow in the footsteps of greatness. Fresh color trims the clean, classic materials, injecting a dose of newness into the familiar design.',
//     price: 120.00,
//     sale_price: null,
//     category_id: '', // Will be filled dynamically
//     brand: 'Jordan',
//     colors: ['Black', 'Red', 'White'],
//     sizes: ['7', '8', '9', '10', '11', '12'],
//     images: [
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/kids-shoes/pexels-photo-2048548.jpeg',
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/kids-shoes/pexels-photo-2421374.jpeg',
//     ],
//     stock: 25,
//     is_featured: true,
//     is_new: false,
//     rating: 4.9,
//     reviews_count: 190,
//   },
//   {
//     name: 'Nike React Infinity Run Flyknit 3',
//     slug: 'nike-react-infinity-run-flyknit-3',
//     description: 'The Nike React Infinity Run Flyknit 3 offers a soft and stable ride. It\'s designed to help reduce injury and keep you running.',
//     price: 160.00,
//     sale_price: 130.00,
//     category_id: '', // Will be filled dynamically
//     brand: 'Nike',
//     colors: ['Black', 'White', 'Volt'],
//     sizes: ['7', '8', '9', '10', '11', '12'],
//     images: [
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/kids-shoes/pexels-photo-2529147.jpeg',
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/kids-shoes/pexels-photo-2529148.jpeg',
//     ],
//     stock: 35,
//     is_featured: false,
//     is_new: true,
//     rating: 4.7,
//     reviews_count: 115,
//   },
//   {
//     name: 'Adidas NMD_R1',
//     slug: 'adidas-nmd-r1',
//     description: 'The NMD_R1 combines adidas\' best running technologies with street-ready style. It\'s a modern classic that\'s always in motion.',
//     price: 140.00,
//     sale_price: null,
//     category_id: '', // Will be filled dynamically
//     brand: 'Adidas',
//     colors: ['Black', 'White', 'Grey'],
//     sizes: ['6', '7', '8', '9', '10', '11'],
//     images: [
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/kids-shoes/pexels-photo-267301.jpeg',
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/mens-shoes/flying-colorful-womens-sneaker-isolated-on-white-background-fashionable-stylish-sports-shoe.jpg',
//     ],
//     stock: 45,
//     is_featured: true,
//     is_new: false,
//     rating: 4.6,
//     reviews_count: 92,
//   },
//   {
//     name: 'Puma Cali Dream',
//     slug: 'puma-cali-dream',
//     description: 'The Cali Dream is a fresh take on the classic California silhouette. With a stacked sole and playful details, it\'s perfect for making a statement.',
//     price: 90.00,
//     sale_price: null,
//     category_id: '', // Will be filled dynamically
//     brand: 'Puma',
//     colors: ['White', 'Pink', 'Black'],
//     sizes: ['5', '6', '7', '8', '9'],
//     images: [
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/mens-shoes/pexels-photo-1027130.jpeg',
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/mens-shoes/pexels-photo-1032110.jpeg',
//     ],
//     stock: 50,
//     is_featured: false,
//     is_new: true,
//     rating: 4.5,
//     reviews_count: 68,
//   },
//   {
//     name: 'New Balance 574',
//     slug: 'new-balance-574',
//     description: 'The 574 is a clean and classic sneaker that delivers iconic style and comfort. It\'s a versatile shoe for everyday wear.',
//     price: 80.00,
//     sale_price: null,
//     category_id: '', // Will be filled dynamically
//     brand: 'New Balance',
//     colors: ['Grey', 'Navy', 'Burgundy'],
//     sizes: ['7', '8', '9', '10', '11'],
//     images: [
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/mens-shoes/pexels-photo-1102777.jpeg',
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/mens-shoes/pexels-photo-1159670.jpeg',
//     ],
//     stock: 55,
//     is_featured: false,
//     is_new: false,
//     rating: 4.4,
//     reviews_count: 70,
//   },
//   {
//     name: 'Nike Metcon 8',
//     slug: 'nike-metcon-8',
//     description: 'The Metcon 8 is built for stability and speed. It\'s designed to help you push your limits in the gym and beyond.',
//     price: 130.00,
//     sale_price: 105.00,
//     category_id: '', // Will be filled dynamically
//     brand: 'Nike',
//     colors: ['Black', 'White', 'Volt'],
//     sizes: ['7', '8', '9', '10', '11', '12'],
//     images: [
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/mens-shoes/pexels-photo-1240892.jpeg',
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/mens-shoes/pexels-photo-1280064.jpeg',
//     ],
//     stock: 28,
//     is_featured: true,
//     is_new: true,
//     rating: 4.7,
//     reviews_count: 110,
//   },
//   {
//     name: 'Adidas Forum Low',
//     slug: 'adidas-forum-low',
//     description: 'The Forum Low brings back the iconic \'80s basketball style. With its classic design and premium materials, it\'s a timeless sneaker.',
//     price: 100.00,
//     sale_price: null,
//     category_id: '', // Will be filled dynamically
//     brand: 'Adidas',
//     colors: ['White', 'Blue', 'Red'],
//     sizes: ['6', '7', '8', '9', '10', '11'],
//     images: [
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/mens-shoes/pexels-photo-1335463.jpeg',
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/womens-shoes/pexels-photo-134064.jpeg',
//     ],
//     stock: 40,
//     is_featured: false,
//     is_new: false,
//     rating: 4.6,
//     reviews_count: 88,
//   },
//   {
//     name: 'Puma Mayze',
//     slug: 'puma-mayze',
//     description: 'The Mayze is all about attitude. With a stacked sole and bold design, it\'s a statement shoe for those who dare to be different.',
//     price: 100.00,
//     sale_price: null,
//     category_id: '', // Will be filled dynamically
//     brand: 'Puma',
//     colors: ['White', 'Black', 'Beige'],
//     sizes: ['5', '6', '7', '8', '9'],
//     images: [
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/womens-shoes/pexels-photo-137603.jpeg',
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/womens-shoes/pexels-photo-1407354.jpeg',
//     ],
//     stock: 30,
//     is_featured: false,
//     is_new: true,
//     rating: 4.5,
//     reviews_count: 60,
//   },
//   {
//     name: 'Nike Air Zoom Pegasus 39',
//     slug: 'nike-air-zoom-pegasus-39',
//     description: 'The Pegasus 39 delivers a comfortable and intuitive design. It\'s a versatile trainer for every run, with a responsive feel and supportive fit.',
//     price: 120.00,
//     sale_price: 95.00,
//     category_id: '', // Will be filled dynamically
//     brand: 'Nike',
//     colors: ['Black', 'White', 'Pink'],
//     sizes: ['6', '7', '8', '9', '10', '11'],
//     images: [
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/womens-shoes/pexels-photo-1445696.jpeg',
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/womens-shoes/pexels-photo-1449844.jpeg',
//     ],
//     stock: 48,
//     is_featured: true,
//     is_new: false,
//     rating: 4.8,
//     reviews_count: 140,
//   },
//   {
//     name: 'Adidas Superstar',
//     slug: 'adidas-superstar',
//     description: 'The adidas Superstar shoe has been an icon for over 50 years. The shell-toe sneaker is a symbol of street style and culture.',
//     price: 90.00,
//     sale_price: null,
//     category_id: '', // Will be filled dynamically
//     brand: 'Adidas',
//     colors: ['White', 'Black'],
//     sizes: ['6', '7', '8', '9', '10', '11'],
//     images: [
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/womens-shoes/pexels-photo-1478442.jpeg',
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/womens-shoes/pexels-photo-1503009.jpeg',
//     ],
//     stock: 65,
//     is_featured: false,
//     is_new: true,
//     rating: 4.7,
//     reviews_count: 105,
//   },
//   {
//     name: 'Puma Future Rider Play On',
//     slug: 'puma-future-rider-play-on',
//     description: 'The Future Rider Play On is all about playful, vibrant style. With a lightweight design and shock-absorbing Federbein outsole, it\'s ready for anything.',
//     price: 80.00,
//     sale_price: null,
//     category_id: '', // Will be filled dynamically
//     brand: 'Puma',
//     colors: ['White', 'Blue', 'Red'],
//     sizes: ['7', '8', '9', '10'],
//     images: [
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/womens-shoes/pexels-photo-15300927.jpeg',
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/kids-shoes/pexels-photo-1598505.jpeg',
//     ],
//     stock: 38,
//     is_featured: false,
//     is_new: false,
//     rating: 4.5,
//     reviews_count: 75,
//   },
//   {
//     name: 'Nike Air Vapormax Flyknit 3',
//     slug: 'nike-air-vapormax-flyknit-3',
//     description: 'The Nike Air VaporMax Flyknit 3 blends two icons for a new look. The Flyknit upper is breathable and supportive, while the VaporMax Air technology provides lightweight cushioning.',
//     price: 200.00,
//     sale_price: 160.00,
//     category_id: '', // Will be filled dynamically
//     brand: 'Nike',
//     colors: ['Black', 'White', 'Grey'],
//     sizes: ['7', '8', '9', '10', '11', '12'],
//     images: [
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/kids-shoes/pexels-photo-1598508.jpeg',
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/kids-shoes/pexels-photo-186035.jpeg',
//     ],
//     stock: 22,
//     is_featured: true,
//     is_new: true,
//     rating: 4.9,
//     reviews_count: 160,
//   },
//   {
//     name: 'Adidas Continental 80',
//     slug: 'adidas-continental-80',
//     description: 'The Continental 80 brings back the retro look of indoor trainers from the 1980s. With a soft leather upper and a distinctive two-tone stripe, it\'s a timeless classic.',
//     price: 80.00,
//     sale_price: null,
//     category_id: '', // Will be filled dynamically
//     brand: 'Adidas',
//     colors: ['White', 'Blue', 'Red'],
//     sizes: ['6', '7', '8', '9', '10', '11'],
//     images: [
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/kids-shoes/pexels-photo-2048548.jpeg',
//       'https://pwyzxwidebovzxwdxoep.supabase.co/storage/v1/object/public/product-images/products/kids-shoes/pexels-photo-2421374.jpeg',
//     ],
//     stock: 50,
//     is_featured: false,
//     is_new: false,
//     rating: 4.6,
//     reviews_count: 85,
//   },
// ];